name: SmileyCoin CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu_no_gui:
    runs-on: ubuntu-20.04
    steps:
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libdb5.3++-dev libboost-all-dev libssl-dev libtool autoconf pkg-config
    - uses: actions/checkout@v2
    - name: configure
      run: ./autogen.sh && ./configure --with-gui=no
    - name: make
      run: make
    - name: make check
      run: make check

  ubuntu_gui:
    runs-on: ubuntu-20.04
    steps:
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libdb5.3++-dev libboost-all-dev libssl-dev libtool autoconf pkg-config
        sudo apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
    - uses: actions/checkout@v2
    - name: configure
      run: ./autogen.sh && ./configure
    - name: make
      run: make
    - name: make check
      run: make check

  ubuntu_:
    runs-on: ubuntu-20.04
    steps:
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake autoconf pkg-config bsdmainutils curl git
        sudo apt-get install -y g++-mingw-w64-x86-64
    - uses: actions/checkout@v2
    - name: depends
      run: cd depends && make HOST=x86_64-w64-mingw32
    - name: configure
      run: ./autogen.sh && CONFIG_SITE=$PWD/depends/x86_64-w64-ming32/share/config.site ./configure --prefix=/
    - name: make
      run: make
    - name: make check
      run: make check
